import fs from 'node:fs/promises';
import path from 'node:path';

import { saveFile, saveTsFile } from 'src/codegen/tools';
import type { ComponentConfig } from 'src/codegen/ComponentConfig';

async function getComponentList() {
  const out: { [folder: string]: string } = {};
  const files = await fs.readdir('src/layout');
  for (const file of files) {
    const stat = await fs.stat(path.join('src/layout', file));
    if (stat.isDirectory()) {
      if (file === 'Address') {
        // Address is a special case, because we once named it 'AddressComponent', without any over the other components
        // having that suffix. We need to keep this for backwards compatibility, but our folder structure uses the name
        // without the suffix.
        out[file] = 'AddressComponent';
        continue;
      }

      out[file] = file;
    }
  }

  return out;
}

const useNewTypes = false; // TODO: Remove this once we've migrated to the new types

(async () => {
  const componentList = await getComponentList();
  const sortedKeys = Object.keys(componentList).sort((a, b) => a.localeCompare(b));
  const componentIndex = [
    '// This file is generated by running `yarn gen`',
    '',
    ...sortedKeys.map(
      (key) =>
        `import { Config as ${key}Config } from 'src/layout/${key}/${useNewTypes ? 'config.generated' : 'index'}';`,
    ),
    ...sortedKeys.map(
      (key) =>
        `import type { TypeConfig as ${key}TypeConfig } from 'src/layout/${key}/${
          useNewTypes ? 'config.generated' : 'index'
        }';`,
    ),
    '',
    `export const ComponentConfigs = {`,
    ...sortedKeys.map((key) => `  ${componentList[key]}: ${key}Config,`),
    `};`,
    '',
    `export type ComponentTypeConfigs = {`,
    ...sortedKeys.map((key) => `  ${componentList[key]}: ${key}TypeConfig;`),
    `};`,
  ];

  const promises: Promise<void>[] = [];
  promises.push(saveFile('src/layout/components.generated.ts', componentIndex.join('\n')));

  for (const key of sortedKeys) {
    const config: ComponentConfig = (await import(`src/layout/${key}/config`)).Config;
    config.setType(componentList[key], key);
    const tsPath = `src/layout/${key}/config.generated.ts`;
    const content = config.toTypeScript();
    promises.push(saveTsFile(tsPath, content));

    const jsonSchemaPath = `src/layout/${key}/config.generated.schema.json`;
    const jsonSchemaContent = JSON.stringify(config.toJsonSchema(), null, 2);
    promises.push(saveFile(jsonSchemaPath, jsonSchemaContent));
  }

  await Promise.all(promises);
})();
