name: Add new issues to Team Apps project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to Team Altinn Studio project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@27022a19346d0433f2b9859dd2b69d38f4277808 # main
        with:
          project-url: https://github.com/orgs/Altinn/projects/164
          github-token: ${{ secrets.ASSIGN_PROJECT_TOKEN }}
