name: Build and run unit tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install dependencies
        working-directory: src
        env:
          GITHUB_PACKAGES_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: yarn --immutable

      - name: run build
        working-directory: src/altinn-app-frontend
        run: yarn build

      - name: run eslint
        working-directory: src
        run: yarn lint

      - name: run tests
        working-directory: src
        run: yarn test --coverage

      - name: Save PR details
        run: |
          mkdir -p ./pr-details
          echo ${{ github.event.number }} > ./pr-details/NR
          echo -n ${{ github.event.pull_request.head.sha }} > ./pr-details/SHA

      # SonarCloud scan is run in a separate workflow when coming from a PR
      - name: Upload code coverage reports
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: code-coverage
          # need to keep * in paths to avoid paths being flattened to the common ancestor, ref https://github.com/actions/upload-artifact#upload-using-multiple-paths-and-exclusions
          path: |
            pr-details/
            src*/altinn-app-frontend/coverage/lcov.info
            src*/shared/coverage/lcov.info

      - name: SonarCloud Scan
        if: github.ref == 'refs/heads/main'
        with:
          projectBaseDir: app-frontend
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
