name: "Label Check"
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if at least one label matches the pattern "kind/*"
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels;
            const hasMatchingLabel = labels.some(label => /^kind\/.*/.test(label.name));
            if (!hasMatchingLabel) {
              core.setFailed('The PR must have at least one label matching the pattern "kind/*".');
            }
