name: Cypress

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'test/**'
      - 'yarn.lock'
      - '.github/workflows/cypress.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'test/**'
      - 'yarn.lock'
      - '.github/workflows/cypress.yml'

  workflow_dispatch:

jobs:
  install:
    name: Internal
    if: |
      github.repository_owner == 'Altinn' &&
      (github.event_name != 'pull_request' && github.event.repository.fork == false) ||
      (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List all files
        run: ls -R

      - name: Install dependencies
        run: yarn --immutable

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          runTests: false
          build: yarn run build

      - name: List all files in dist
        run: ls -R dist

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: dist

  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            test
            .yarn

      - name: Increase file watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Cypress run
        env:
          CYPRESS_PROJECT_ID: y2jhp6
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARALLEL_TOTAL: 3
          PERCY_PARALLEL_NONCE: ${{ github.run_id }}-${{ github.run_attempt }}
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server dist --cors='*' & npx percy exec --parallel
          record: true
          parallel: true
          group: altinn-app-frontend
          tag: altinn-app-frontend
          browser: chrome
          ci-build-id: ${{ github.run_id }}-${{ github.run_attempt }}
          spec: test/e2e/integration
          env: environment=tt02

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs
          path: test/logs/*

  external:
    if: |
     github.repository_owner == 'Altinn' &&
     (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    runs-on: ubuntu-latest
    name: External

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Increase file watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --immutable

      - name: Build
        run: yarn build

      - name: Verify cypress and run tests
        run: "
          npx cypress verify\n
          bash -c 'yarn serve 8080 >/dev/null &'\n
         bash -c 'npx cypress run
              --spec test/e2e/integration
              --config watchForFileChanges=false
              --env environment=tt02'
        "

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: external-logs
          path: |
            test/logs/*
            test/screenshots/*
            test/videos/*
