name: Publish to CDN
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: app-frontend
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install dependencies
        working-directory: app-frontend
        env:
          GITHUB_PACKAGES_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: yarn --immutable

      - name: run build
        working-directory: app-frontend
        run: yarn build

      - name: Checkout Altinn-CDN repository
        uses: actions/checkout@v3
        with:
          repository: 'Altinn/altinn-cdn'
          token: ${{secrets.ALTINN_CDN_TOKEN}}
          path: cdn

      - name: Run release script
        working-directory: app-frontend
        if: "!github.event.release.prerelease"
        run: bash .github/scripts/release.sh --frontend . --cdn ../cdn --commit

      - name: Run release script (pre-release)
        working-directory: app-frontend
        if: "github.event.release.prerelease"
        run: bash .github/scripts/release.sh --frontend . --cdn ../cdn --commit --pre-release

      - name: Push to CDN
        working-directory: cdn
        run: git push

      - name: Deploy files to azure CDN (staging)
        uses: azure/CLI@v1
        if: "!github.event.release.prerelease"
        with:
          azcliversion: 2.44.1
          inlineScript: |
            cd cdn
            az storage copy -s toolkits -d https://${{ secrets.STAGING_STORAGEACCOUNT_NAME }}.blob.core.windows.net/app-frontend${{ secrets.STAGING_ALTINN_CDN_SAS_TOKEN }} --recursive
            cd schemas/json
            az storage copy -s layout/ -d https://${{ secrets.STAGING_STORAGEACCOUNT_NAME }}.blob.core.windows.net/app-frontend${{ secrets.STAGING_ALTINN_CDN_SAS_TOKEN }} --recursive
            az storage copy -s component/ -d https://${{ secrets.STAGING_STORAGEACCOUNT_NAME }}.blob.core.windows.net/app-frontend${{ secrets.STAGING_ALTINN_CDN_SAS_TOKEN }} --recursive

      - name: Deploy files to azure CDN (staging) (prerelease)
        uses: azure/CLI@v1
        if: "github.event.release.prerelease"
        with:
          azcliversion: 2.44.1
          inlineScript: |
            cd cdn
            az storage copy -s toolkits -d https://${{ secrets.STAGING_STORAGEACCOUNT_NAME }}.blob.core.windows.net/app-frontend${{ secrets.STAGING_ALTINN_CDN_SAS_TOKEN }} --recursive