// This file is generated by running src/layout/components.gen.ts

import { Config as ActionButtonConfig } from 'src/layout/ActionButton/index';
import { Config as AddressConfig } from 'src/layout/Address/index';
import { Config as AttachmentListConfig } from 'src/layout/AttachmentList/index';
import { Config as ButtonConfig } from 'src/layout/Button/index';
import { Config as ButtonGroupConfig } from 'src/layout/ButtonGroup/index';
import { Config as CheckboxesConfig } from 'src/layout/Checkboxes/index';
import { Config as CustomConfig } from 'src/layout/Custom/index';
import { Config as DatepickerConfig } from 'src/layout/Datepicker/index';
import { Config as DropdownConfig } from 'src/layout/Dropdown/index';
import { Config as FileUploadConfig } from 'src/layout/FileUpload/index';
import { Config as FileUploadWithTagConfig } from 'src/layout/FileUploadWithTag/index';
import { Config as GridConfig } from 'src/layout/Grid/index';
import { Config as GroupConfig } from 'src/layout/Group/index';
import { Config as HeaderConfig } from 'src/layout/Header/index';
import { Config as IFrameConfig } from 'src/layout/IFrame/index';
import { Config as ImageConfig } from 'src/layout/Image/index';
import { Config as InputConfig } from 'src/layout/Input/index';
import { Config as InstanceInformationConfig } from 'src/layout/InstanceInformation/index';
import { Config as InstantiationButtonConfig } from 'src/layout/InstantiationButton/index';
import { Config as LikertConfig } from 'src/layout/Likert/index';
import { Config as LinkConfig } from 'src/layout/Link/index';
import { Config as ListConfig } from 'src/layout/List/index';
import { Config as MapConfig } from 'src/layout/Map/index';
import { Config as MultipleSelectConfig } from 'src/layout/MultipleSelect/index';
import { Config as NavigationBarConfig } from 'src/layout/NavigationBar/index';
import { Config as NavigationButtonsConfig } from 'src/layout/NavigationButtons/index';
import { Config as PanelConfig } from 'src/layout/Panel/index';
import { Config as ParagraphConfig } from 'src/layout/Paragraph/index';
import { Config as PrintButtonConfig } from 'src/layout/PrintButton/index';
import { Config as RadioButtonsConfig } from 'src/layout/RadioButtons/index';
import { Config as SummaryConfig } from 'src/layout/Summary/index';
import { Config as TextAreaConfig } from 'src/layout/TextArea/index';

export const components = {
  ActionButton: ActionButtonConfig.def,
  AddressComponent: AddressConfig.def,
  AttachmentList: AttachmentListConfig.def,
  Button: ButtonConfig.def,
  ButtonGroup: ButtonGroupConfig.def,
  Checkboxes: CheckboxesConfig.def,
  Custom: CustomConfig.def,
  Datepicker: DatepickerConfig.def,
  Dropdown: DropdownConfig.def,
  FileUpload: FileUploadConfig.def,
  FileUploadWithTag: FileUploadWithTagConfig.def,
  Grid: GridConfig.def,
  Group: GroupConfig.def,
  Header: HeaderConfig.def,
  IFrame: IFrameConfig.def,
  Image: ImageConfig.def,
  Input: InputConfig.def,
  InstanceInformation: InstanceInformationConfig.def,
  InstantiationButton: InstantiationButtonConfig.def,
  Likert: LikertConfig.def,
  Link: LinkConfig.def,
  List: ListConfig.def,
  Map: MapConfig.def,
  MultipleSelect: MultipleSelectConfig.def,
  NavigationBar: NavigationBarConfig.def,
  NavigationButtons: NavigationButtonsConfig.def,
  Panel: PanelConfig.def,
  Paragraph: ParagraphConfig.def,
  PrintButton: PrintButtonConfig.def,
  RadioButtons: RadioButtonsConfig.def,
  Summary: SummaryConfig.def,
  TextArea: TextAreaConfig.def,
};

export type ComponentLayoutTypeMap = {
  ActionButton: (typeof ActionButtonConfig)['types']['layout'];
  AddressComponent: (typeof AddressConfig)['types']['layout'];
  AttachmentList: (typeof AttachmentListConfig)['types']['layout'];
  Button: (typeof ButtonConfig)['types']['layout'];
  ButtonGroup: (typeof ButtonGroupConfig)['types']['layout'];
  Checkboxes: (typeof CheckboxesConfig)['types']['layout'];
  Custom: (typeof CustomConfig)['types']['layout'];
  Datepicker: (typeof DatepickerConfig)['types']['layout'];
  Dropdown: (typeof DropdownConfig)['types']['layout'];
  FileUpload: (typeof FileUploadConfig)['types']['layout'];
  FileUploadWithTag: (typeof FileUploadWithTagConfig)['types']['layout'];
  Grid: (typeof GridConfig)['types']['layout'];
  Group: (typeof GroupConfig)['types']['layout'];
  Header: (typeof HeaderConfig)['types']['layout'];
  IFrame: (typeof IFrameConfig)['types']['layout'];
  Image: (typeof ImageConfig)['types']['layout'];
  Input: (typeof InputConfig)['types']['layout'];
  InstanceInformation: (typeof InstanceInformationConfig)['types']['layout'];
  InstantiationButton: (typeof InstantiationButtonConfig)['types']['layout'];
  Likert: (typeof LikertConfig)['types']['layout'];
  Link: (typeof LinkConfig)['types']['layout'];
  List: (typeof ListConfig)['types']['layout'];
  Map: (typeof MapConfig)['types']['layout'];
  MultipleSelect: (typeof MultipleSelectConfig)['types']['layout'];
  NavigationBar: (typeof NavigationBarConfig)['types']['layout'];
  NavigationButtons: (typeof NavigationButtonsConfig)['types']['layout'];
  Panel: (typeof PanelConfig)['types']['layout'];
  Paragraph: (typeof ParagraphConfig)['types']['layout'];
  PrintButton: (typeof PrintButtonConfig)['types']['layout'];
  RadioButtons: (typeof RadioButtonsConfig)['types']['layout'];
  Summary: (typeof SummaryConfig)['types']['layout'];
  TextArea: (typeof TextAreaConfig)['types']['layout'];
};

export type ComponentNodeTypeMap = {
  ActionButton: (typeof ActionButtonConfig)['types']['node'];
  AddressComponent: (typeof AddressConfig)['types']['node'];
  AttachmentList: (typeof AttachmentListConfig)['types']['node'];
  Button: (typeof ButtonConfig)['types']['node'];
  ButtonGroup: (typeof ButtonGroupConfig)['types']['node'];
  Checkboxes: (typeof CheckboxesConfig)['types']['node'];
  Custom: (typeof CustomConfig)['types']['node'];
  Datepicker: (typeof DatepickerConfig)['types']['node'];
  Dropdown: (typeof DropdownConfig)['types']['node'];
  FileUpload: (typeof FileUploadConfig)['types']['node'];
  FileUploadWithTag: (typeof FileUploadWithTagConfig)['types']['node'];
  Grid: (typeof GridConfig)['types']['node'];
  Group: (typeof GroupConfig)['types']['node'];
  Header: (typeof HeaderConfig)['types']['node'];
  IFrame: (typeof IFrameConfig)['types']['node'];
  Image: (typeof ImageConfig)['types']['node'];
  Input: (typeof InputConfig)['types']['node'];
  InstanceInformation: (typeof InstanceInformationConfig)['types']['node'];
  InstantiationButton: (typeof InstantiationButtonConfig)['types']['node'];
  Likert: (typeof LikertConfig)['types']['node'];
  Link: (typeof LinkConfig)['types']['node'];
  List: (typeof ListConfig)['types']['node'];
  Map: (typeof MapConfig)['types']['node'];
  MultipleSelect: (typeof MultipleSelectConfig)['types']['node'];
  NavigationBar: (typeof NavigationBarConfig)['types']['node'];
  NavigationButtons: (typeof NavigationButtonsConfig)['types']['node'];
  Panel: (typeof PanelConfig)['types']['node'];
  Paragraph: (typeof ParagraphConfig)['types']['node'];
  PrintButton: (typeof PrintButtonConfig)['types']['node'];
  RadioButtons: (typeof RadioButtonsConfig)['types']['node'];
  Summary: (typeof SummaryConfig)['types']['node'];
  TextArea: (typeof TextAreaConfig)['types']['node'];
};
